package com.property.keys.entities;

public enum Action {
    ADDED_PROPERTY, DELETED_PROPERTY, UPDATED_PROPERTY, MOVED_TO_TRASH_PROPERTY, RESTORED_FROM_TRASH_PROPERTY,
    ADDED_KEY, DELETED_KEY, CHECKED_IN, CHECKED_OUT
}
