package com.property.keys.entities;

public enum Action {
    LIKED_PROPERTY, UNLIKED_PROPERTY,
    ADDED_PROPERTY, DELETED_PROPERTY, UPDATED_PROPERTY,
    ADDED_KEY, DELETED_KEY, CHECKED_IN, CHECKED_OUT
}
